### ISSUE TITLE
Did addChangeHandler was removed forever?

### ISSUE THREAD

**Issue by solovey255** [sbx320/lua_utils#10]
Great job sbx320, your lib is very usefull for me. I saw function addChangeHandler at wiki, but cant find it in current sources. May be, is equivalent exists now?

**Comment by sbx320** [comment]
There's no equivalent in the current version. You can find the old one here:
https://github.com/sbx320/lua_utils/blob/38ebec46f558e28ad36d1601d291530e0b77a635/classlib.lua#L341

My original intention was to move it out of the file as it didn't quite fit in with the rest of the code. However that never happened.
